import { Injectable } from '@nestjs/common';
import { createHash } from 'node:crypto';

export interface EngineConfiguration {
  adminPort: number;
  smsboxPort: number;
  adminSecretRef: string;
  logLevel: 0 | 1 | 2 | 3 | 4;
  sqlbox?: {
    enabled: boolean;
    host: string;
    port: number;
    database: string;
    usernameEnv: string;
    passwordEnv: string;
  };
  smsc: Array<{
    id: string;
    type: 'smpp' | 'http' | 'fake' | 'at';
    host?: string;
    port?: number;
    usernameSecretRef?: string;
    enabled: boolean;
  }>;
}
@Injectable()
export class ConfigurationGeneratorService {
  validate(model: EngineConfiguration): string[] {
    const errors: string[] = [];
    if (model.adminPort === model.smsboxPort) errors.push('adminPort and smsboxPort must differ');
    if (!model.adminSecretRef.startsWith('secret://'))
      errors.push('adminSecretRef must be a secret reference');
    if (model.sqlbox?.enabled) {
      if (!model.sqlbox.host || !model.sqlbox.database)
        errors.push('SQLBox host and database are required');
      if (
        !/^[A-Z][A-Z0-9_]+$/.test(model.sqlbox.usernameEnv) ||
        !/^[A-Z][A-Z0-9_]+$/.test(model.sqlbox.passwordEnv)
      )
        errors.push('SQLBox credentials must be environment variable names');
    }
    const ids = new Set<string>();
    for (const smsc of model.smsc) {
      if (ids.has(smsc.id)) errors.push(`duplicate SMSC id: ${smsc.id}`);
      ids.add(smsc.id);
      if (smsc.type !== 'fake' && (!smsc.host || !smsc.port))
        errors.push(`${smsc.id} requires host and port`);
      if (smsc.usernameSecretRef && !smsc.usernameSecretRef.startsWith('secret://'))
        errors.push(`${smsc.id} credential must be a secret reference`);
    }
    return errors;
  }
  generate(model: EngineConfiguration): { content: string; checksum: string } {
    const errors = this.validate(model);
    if (errors.length) throw new Error(errors.join('; '));
    const lines = [
      `# Generated by JKANNEL. Do not edit by hand.`,
      `group = core`,
      `admin-port = ${model.adminPort}`,
      `smsbox-port = ${model.smsboxPort}`,
      'admin-password = ${KAMEX_ADMIN_PASSWORD}',
      'status-password = ${KAMEX_STATUS_PASSWORD}',
      `log-level = ${model.logLevel}`,
      'log-format = json',
    ];
    for (const smsc of [...model.smsc]
      .filter((x) => x.enabled)
      .sort((a, b) => a.id.localeCompare(b.id))) {
      lines.push('', `group = smsc`, `smsc = ${smsc.type}`, `smsc-id = ${smsc.id}`);
      if (smsc.host) lines.push(`host = ${smsc.host}`);
      if (smsc.port) lines.push(`port = ${smsc.port}`);
    }
    if (model.sqlbox?.enabled)
      lines.push(
        '',
        '# SQLBox PostgreSQL connection (consumed by the SQLBox process)',
        `group = pgsql-connection`,
        'id = jkannel-sqlbox',
        `host = ${model.sqlbox.host}`,
        `port = ${model.sqlbox.port}`,
        `database = ${model.sqlbox.database}`,
        `username = \${${model.sqlbox.usernameEnv}}`,
        `password = \${${model.sqlbox.passwordEnv}}`,
      );
    const content = `${lines.join('\n')}\n`;
    return { content, checksum: createHash('sha256').update(content).digest('hex') };
  }
}
