BEGIN;
CREATE TYPE engine_support_state AS ENUM ('supported','unsupported','unknown');
CREATE TYPE engine_action_state AS ENUM ('requested','awaiting_approval','approved','executing','succeeded','failed','cancelled','rolled_back');

CREATE TABLE engine_instances (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id bigint NOT NULL REFERENCES tenants(id), name text NOT NULL, engine_type text NOT NULL, endpoint_reference text NOT NULL, credential_reference text, desired_state text NOT NULL DEFAULT 'unknown', engine_version text, engine_build text, is_enabled boolean NOT NULL DEFAULT true, created_by text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (tenant_id,name));
CREATE TABLE adapter_instances (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id bigint NOT NULL REFERENCES tenants(id), engine_instance_id uuid NOT NULL REFERENCES engine_instances(id), implementation text NOT NULL, adapter_version text NOT NULL, adapter_build text NOT NULL, created_by text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (tenant_id,engine_instance_id,implementation,adapter_version,adapter_build));
CREATE TABLE engine_capability_snapshots (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id bigint NOT NULL REFERENCES tenants(id), engine_instance_id uuid NOT NULL REFERENCES engine_instances(id), adapter_instance_id uuid NOT NULL REFERENCES adapter_instances(id), registry_version text NOT NULL, engine_version text NOT NULL, engine_build text NOT NULL, adapter_version text NOT NULL, adapter_build text NOT NULL, observed_at timestamptz NOT NULL, expires_at timestamptz NOT NULL, supersedes_id uuid REFERENCES engine_capability_snapshots(id), evidence_reference text, created_by text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(engine_instance_id,adapter_instance_id,registry_version,observed_at), CHECK(expires_at>observed_at));
CREATE TABLE engine_capability_entries (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id bigint NOT NULL REFERENCES tenants(id), snapshot_id uuid NOT NULL REFERENCES engine_capability_snapshots(id), capability_id text NOT NULL, support engine_support_state NOT NULL, owner text NOT NULL, source text NOT NULL, constraints jsonb NOT NULL DEFAULT '{}', evidence_reference text, created_by text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(snapshot_id,capability_id));

CREATE TABLE engine_runtime_snapshots (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id bigint NOT NULL REFERENCES tenants(id), engine_instance_id uuid NOT NULL REFERENCES engine_instances(id), adapter_instance_id uuid NOT NULL REFERENCES adapter_instances(id), capability_snapshot_id uuid REFERENCES engine_capability_snapshots(id), runtime_state text NOT NULL, health_state text NOT NULL, counters jsonb NOT NULL DEFAULT '{}', source_freshness_ms bigint, observed_at timestamptz NOT NULL, created_by text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), CHECK(source_freshness_ms IS NULL OR source_freshness_ms>=0));
CREATE TABLE engine_connection_snapshots (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id bigint NOT NULL REFERENCES tenants(id), engine_instance_id uuid NOT NULL REFERENCES engine_instances(id), adapter_instance_id uuid NOT NULL REFERENCES adapter_instances(id), capability_snapshot_id uuid REFERENCES engine_capability_snapshots(id), connection_identity text NOT NULL, connection_state text NOT NULL, statistics jsonb NOT NULL DEFAULT '{}', observed_at timestamptz NOT NULL, created_by text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE engine_queue_snapshots (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id bigint NOT NULL REFERENCES tenants(id), engine_instance_id uuid NOT NULL REFERENCES engine_instances(id), adapter_instance_id uuid NOT NULL REFERENCES adapter_instances(id), capability_snapshot_id uuid REFERENCES engine_capability_snapshots(id), queue_identity text NOT NULL, source text NOT NULL, queue_state text NOT NULL, depth bigint, observed_at timestamptz NOT NULL, created_by text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), CHECK(depth IS NULL OR depth>=0));

CREATE TABLE engine_lifecycle_actions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id bigint NOT NULL REFERENCES tenants(id), engine_instance_id uuid NOT NULL REFERENCES engine_instances(id), adapter_instance_id uuid NOT NULL REFERENCES adapter_instances(id), capability_snapshot_id uuid NOT NULL REFERENCES engine_capability_snapshots(id), actor_id text NOT NULL, approval_reference text, idempotency_key text NOT NULL, operation_id text NOT NULL, operation_scope jsonb NOT NULL DEFAULT '{}', state engine_action_state NOT NULL DEFAULT 'requested', requested_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), created_by text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,engine_instance_id,idempotency_key));
CREATE TABLE engine_lifecycle_results (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id bigint NOT NULL REFERENCES tenants(id), action_id uuid NOT NULL REFERENCES engine_lifecycle_actions(id), outcome text NOT NULL, response jsonb NOT NULL DEFAULT '{}', evidence_reference text, started_at timestamptz, completed_at timestamptz, created_by text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), CHECK(completed_at IS NULL OR started_at IS NULL OR completed_at>=started_at));
CREATE TABLE engine_sync_cursors (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id bigint NOT NULL REFERENCES tenants(id), engine_instance_id uuid NOT NULL REFERENCES engine_instances(id), source_kind text NOT NULL, source_identity text NOT NULL, watermark jsonb, lag_ms bigint, last_attempt_at timestamptz, last_success_at timestamptz, last_failure_at timestamptz, last_failure_reason text, created_by text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,engine_instance_id,source_kind,source_identity), CHECK(lag_ms IS NULL OR lag_ms>=0));

CREATE INDEX engine_runtime_observed_idx ON engine_runtime_snapshots(tenant_id,engine_instance_id,observed_at DESC);
CREATE INDEX engine_connection_observed_idx ON engine_connection_snapshots(tenant_id,engine_instance_id,observed_at DESC);
CREATE INDEX engine_queue_observed_idx ON engine_queue_snapshots(tenant_id,engine_instance_id,observed_at DESC);
CREATE VIEW active_engine_capability_manifests AS SELECT DISTINCT ON (tenant_id,engine_instance_id) * FROM engine_capability_snapshots WHERE expires_at>now() ORDER BY tenant_id,engine_instance_id,observed_at DESC;

CREATE FUNCTION enforce_engine_action_transition() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
IF NEW.state=OLD.state THEN RETURN NEW; END IF;
IF NOT ((OLD.state='requested' AND NEW.state IN ('awaiting_approval','approved','cancelled')) OR (OLD.state='awaiting_approval' AND NEW.state IN ('approved','cancelled')) OR (OLD.state='approved' AND NEW.state IN ('executing','cancelled')) OR (OLD.state='executing' AND NEW.state IN ('succeeded','failed','rolled_back')) OR (OLD.state='succeeded' AND NEW.state='rolled_back')) THEN RAISE EXCEPTION 'invalid engine action transition: % -> %',OLD.state,NEW.state; END IF;
NEW.updated_at=now(); RETURN NEW; END $$;
CREATE TRIGGER engine_action_transition BEFORE UPDATE OF state ON engine_lifecycle_actions FOR EACH ROW EXECUTE FUNCTION enforce_engine_action_transition();

DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['engine_instances','adapter_instances','engine_capability_snapshots','engine_capability_entries','engine_runtime_snapshots','engine_connection_snapshots','engine_queue_snapshots','engine_lifecycle_actions','engine_lifecycle_results','engine_sync_cursors'] LOOP EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',t); EXECUTE format('CREATE POLICY tenant_isolation ON %I USING (tenant_id=nullif(current_setting(''app.tenant_id'',true),'''')::bigint) WITH CHECK (tenant_id=nullif(current_setting(''app.tenant_id'',true),'''')::bigint)',t); END LOOP; END $$;
COMMIT;
